"""
Example: Running FoodGuard AI Agents with vLLM (Qwen3-4B)
This script demonstrates how to use the updated agents with the new LLM setup.
"""

import sys
import os

# Add project to path
sys.path.insert(0, '/home/souvik/projects/AI/food-guard-ai')

# Step 1: Configure LLM
print("=" * 70)
print("STEP 1: Configure LLM Environment")
print("=" * 70)

from agents.llm_client import configure_llm_env, get_llm_client

# Configure environment variables
configure_llm_env(
    base_url="http://localhost:8000/v1",
    api_key="abc-123"
)

# Get LLM client
llm = get_llm_client()
print("✓ LLM configured successfully\n")


# Step 2: Initialize Agent State
print("=" * 70)
print("STEP 2: Initialize Investigation State")
print("=" * 70)

from agents.state import FoodInvestigationState

initial_state = FoodInvestigationState(
    food_type="milk",
    batch_name="Batch-001",

    # Simulated sensor data (in real scenario, from ML models)
    vision_result={
        "deposit_type": "fine_crystals",
        "score": 0.72,
        "label": "urea_suspected"
    },
    aroma_result={
        "compounds": {"ammonia": 0.85, "alcohol": 0.30},
        "score": 0.79,
        "label": "ammonia_spike"
    },
    taste_result={
        "compounds": {"saltiness": 0.88, "sourness": 0.35},
        "score": 0.82,
        "label": "high_salinity"
    },

    # IDs will be generated by supervisor
    batch_id=None,
    investigation_id=None,
    vision_id=None,
    aroma_id=None,
    taste_id=None,
    correlation_id=None,
    passport_id=None,
    certificate_id=None,
    errors=[]
)

print(f"✓ Initial state created for batch: {initial_state['batch_name']}\n")


# Step 3: Run Supervisor Node
print("=" * 70)
print("STEP 3: Supervisor Node (ID Generation)")
print("=" * 70)

from agents.supervisor import supervisor_node

state = supervisor_node(initial_state)
print(f"✓ Batch ID: {state['batch_id']}")
print(f"✓ Investigation ID: {state['investigation_id']}")
print(f"✓ Correlation ID: {state['correlation_id']}\n")


# Step 4: Run Correlation Agent
print("=" * 70)
print("STEP 4: Correlation Agent (Cross-Modal Reasoning)")
print("=" * 70)

from agents.correlation import correlation_node

try:
    state = correlation_node(state)
    print("Correlation Result:")
    print(f"  - Pattern Type: {state['correlation_result'].get('pattern_type', 'unknown')}")
    print(f"  - Suspected Adulterant: {state['correlation_result'].get('suspected_adulterant', 'unknown')}")
    print(f"  - Confidence Delta: {state['correlation_result'].get('confidence_delta', 0)}")
    print(f"  - Consensus Score: {state['correlation_result'].get('consensus_score', 0)}")
    print()
except Exception as e:
    print(f"⚠ Correlation Agent Error: {e}")
    print("  (Make sure vLLM server is running)\n")


# Step 5: Run Food Safety Agent
print("=" * 70)
print("STEP 5: Food Safety Agent (Verdict Generation)")
print("=" * 70)

from agents.food_safety import food_safety_node

try:
    state = food_safety_node(state)
    print("Investigation Result:")
    print(f"  - Authenticity Score: {state['investigation_result'].get('authenticity_score', 'unknown')}")
    print(f"  - Risk Level: {state['investigation_result'].get('risk_level', 'unknown')}")
    print(f"  - Verdict: {state['investigation_result'].get('verdict', 'unknown')}")
    print(f"  - Suspected Adulterant: {state['investigation_result'].get('suspected_adulterant', 'unknown')}")
    print()
except Exception as e:
    print(f"⚠ Food Safety Agent Error: {e}")
    print("  (Make sure vLLM server is running)\n")


# Step 6: Run Reviewer Agent
print("=" * 70)
print("STEP 6: Reviewer Agent (Confidence Validation)")
print("=" * 70)

from agents.reviewer import reviewer_node

try:
    state = reviewer_node(state)
    print("Review Result:")
    print(f"  - Final Confidence: {state['review_result'].get('final_confidence', 'unknown')}")
    print(f"  - Confidence Adjustment: {state['review_result'].get('confidence_adjustment', 0)}")
    print(f"  - Consensus Level: {state['review_result'].get('consensus_level', 'unknown')}")
    print(f"  - Escalation Needed: {state['review_result'].get('escalation_needed', False)}")
    print()
except Exception as e:
    print(f"⚠ Reviewer Agent Error: {e}")
    print("  (Make sure vLLM server is running)\n")


# Step 7: Run Passport Agent
print("=" * 70)
print("STEP 7: Passport Agent (Certificate Generation)")
print("=" * 70)

from agents.passport import passport_node

try:
    state = passport_node(state)
    print("Passport Result:")
    print(f"  - Passport ID: {state['passport_result'].get('passport_id', 'unknown')}")
    print(f"  - Certificate Hash: {state['passport_result'].get('certificate_hash', 'unknown')[:16]}...")
    print(f"  - Status: {state['passport_result'].get('status', 'unknown')}")
    print()
except Exception as e:
    print(f"⚠ Passport Agent Error: {e}\n")


# Summary
print("=" * 70)
print("INVESTIGATION SUMMARY")
print("=" * 70)
print(f"Batch: {state['batch_name']}")
print(f"Final Verdict: {state.get('investigation_result', {}).get('verdict', 'Inconclusive')}")
print(f"Risk Level: {state.get('investigation_result', {}).get('risk_level', 'Unknown')}")
print(f"Final Confidence: {state.get('review_result', {}).get('final_confidence', 'Unknown')}%")
print("\n✓ Investigation complete!\n")
